# Generated by Django 4.2.3 on 2023-10-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_getnews_topic_id_alter_getnews_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getnews',
            old_name='topic_name',
            new_name='topic_id',
        ),
    ]
