# Generated by Django 4.2.3 on 2023-10-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_getnews_article_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerizedData',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.getnews')),
                ('sum_content', models.TextField(max_length=500)),
            ],
        ),
    ]
