# Generated by Django 4.2.3 on 2023-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerizeddata',
            name='new_topic',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
