# Generated by Django 4.2.3 on 2023-10-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natural', '0002_summerizeddata_new_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summerizeddata',
            old_name='new_topic',
            new_name='news_topic',
        ),
    ]
